"use client";
import { useEffect, useMemo, useState } from "react";

type Metric = { timestamp:string; cpu_percent:number; memory_percent:number; api_latency_ms:number; request_volume:number; http_error_rate:number; db_connection_utilization:number; network_traffic_mbps:number; disk_utilization:number; service_status:string };
type Incident = { incident_id:string; service:string; detected_at:string; primary_signal:string; anomaly_score:number; severity:string; summary:string; supporting_metrics:Record<string,number> };
const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
const fallback: Metric[] = [{timestamp:new Date().toISOString(),cpu_percent:93,memory_percent:82,api_latency_ms:1720,request_volume:1540,http_error_rate:13.8,db_connection_utilization:95,network_traffic_mbps:260,disk_utilization:42,service_status:"degraded"}];

export default function Dashboard() {
  const [metrics, setMetrics] = useState<Metric[]>(fallback); const [incidents, setIncidents] = useState<Incident[]>([]); const [online, setOnline] = useState(false);
  useEffect(() => { Promise.all([fetch(`${API}/telemetry?limit=30`).then(r=>r.json()), fetch(`${API}/incidents`).then(r=>r.json())]).then(([t,i]) => { setMetrics(t.data); setIncidents(i.data); setOnline(true); }).catch(()=>setOnline(false)); }, []);
  const current = metrics.at(-1) || fallback[0]; const latest = useMemo(()=>incidents.slice().reverse().slice(0,5), [incidents]);
  const cards = [["CPU utilization", current.cpu_percent, "%", 85], ["Memory", current.memory_percent, "%", 85], ["API latency", current.api_latency_ms, "ms", 800], ["HTTP errors", current.http_error_rate, "%", 5], ["DB pool", current.db_connection_utilization, "%", 85], ["Request volume", current.request_volume, "/min", 1200]];
  return <main><nav><div className="brand"><span className="mark">◈</span> OPSMIND <b>AI</b></div><div className="live"><i className={online ? "dot" : "dot off"}></i>{online ? "SIMULATION LIVE" : "DEMO MODE"}</div></nav>
    <section className="hero"><div><p className="eyebrow">AGENTIC AIOPS · PHASE 1</p><h1>See the signal.<br/><em>Understand the incident.</em></h1><p className="lead">ML-powered anomaly detection across service telemetry—built for faster operational decisions.</p></div><div className="health"><span>PLATFORM HEALTH</span><strong>{current.service_status === "healthy" ? "Stable" : "Needs attention"}</strong><small>payment-api · synthetic environment</small></div></section>
    <section className="metrics">{cards.map(([label,value,unit,threshold]) => <article key={String(label)} className={Number(value)>Number(threshold) ? "metric alert" : "metric"}><span>{label}</span><strong>{Number(value).toLocaleString()}<small>{unit}</small></strong><div><i style={{width:`${Math.min(Number(value),100)}%`}} /></div><small>{Number(value)>Number(threshold) ? "Above operating threshold" : "Within expected range"}</small></article>)}</section>
    <section className="grid"><div className="panel signal"><div className="panelhead"><div><p className="eyebrow">LIVE TELEMETRY</p><h2>Latency & anomaly profile</h2></div><span>last 30 min</span></div><div className="chart">{metrics.slice(-20).map((m,i)=><div key={m.timestamp} className="bar" style={{height:`${Math.max(8,Math.min(100,m.api_latency_ms/20))}%`}} title={`${m.api_latency_ms}ms`}><i /></div>)}</div><div className="legend"><span><i className="blue"/> API latency</span><span><i className="amber"/> high-risk signal</span></div></div>
      <div className="panel posture"><p className="eyebrow">DETECTION ENGINE</p><h2>Isolation Forest</h2><div className="score">{incidents.length ? Math.max(...incidents.map(i=>i.anomaly_score)).toFixed(2) : "—"}<small>peak anomaly score</small></div><p>Feature-enriched multivariate detection across 8 telemetry signals.</p><div className="pills"><span>CPU</span><span>Latency</span><span>Errors</span><span>DB</span></div></div></section>
    <section className="panel incidents"><div className="panelhead"><div><p className="eyebrow">INCIDENT QUEUE</p><h2>Detected anomalies</h2></div><span>{incidents.length} findings</span></div>{latest.length ? <div className="table"><div className="row header"><span>Severity</span><span>Incident</span><span>Primary signal</span><span>Score</span><span>Detected</span></div>{latest.map(i=><div className="row" key={i.incident_id}><span><b className={`tag ${i.severity}`}>{i.severity}</b></span><span><strong>{i.incident_id}</strong><small>{i.service}</small></span><span>{i.primary_signal}</span><span className="scorecell">{i.anomaly_score.toFixed(2)}</span><span>{new Date(i.detected_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span></div>)}</div> : <p className="empty">Start the API to populate the incident queue.</p>}</section>
    <footer>SYNTHETIC DATA ONLY · NOT PRODUCTION MONITORING · OPSMIND AI MVP</footer></main>;
}
